### PR TITLE
Added support for threshold limit and better accuracy

### PR DESCRIPTION
**Pull request by pranshuag9**
This pull request aims at:
- Solved issue #7.
- Added micro and nano seconds logging of code block execution
- Fixed hardcoded strings with constant strings
- Reformatted the code

### CODE REVIEW

**Comment by JustasB** [comment]
Hi @pranshuag9!

Thanks for the PR! I love the idea of logging only when a threshold is exceeded. 

Will you please update the unit tests to include the new functionality? I would like to maintain 100% coverage.
https://github.com/JustasB/linetimer/blob/master/tests/test_CodeTimer.py

Also please add a section to the readme file with an example using the new threshold parameter:
https://github.com/JustasB/linetimer/blob/master/Readme.md

Otherwise, your code looks great!

**Comment by pranshuag9** [comment]
Test cases are added. Please check.

**Comment by pranshuag9** [comment]
Also updated the Readme file.

**Review by JustasB — APPROVED** [review]
Thank you, looks great

**Comment by pranshuag9** [comment]
Thank you @JustasB. 🙂

**Comment by pranshuag9** [comment]
By when can we see this released on pypi?

**Comment by pranshuag9** [comment]
Thanks 🙂 , it's showing a new release 0.1.5.

**Pull request merged**
